//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_conductor p_conductor;
        
        public static SteamVR_Input_ActionSet_conductor conductor
        {
            get
            {
                return SteamVR_Actions.p_conductor.GetCopy<SteamVR_Input_ActionSet_conductor>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p_conductor = ((SteamVR_Input_ActionSet_conductor)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_conductor>("/actions/conductor")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions.conductor};
        }
    }
}
